FPS = 60
WIDTH = 1366
HEIGHT = 768
TITLE = "Space Checkpoint"
BARLOW = "../res/fonts/barlow.ttf"
TITILLIUM = "../res/fonts/titillium.ttf"
ICON = "../res/logos/blackredbig.png"
WORKTABLE = "../res/assets/worktable.jpg"
WEBBBUTTON = "../res/assets/jwst.png"
WEBB = "../res/images/webb.jpg"
MMBG = "../res/sounds/mmbg.ogg"
IGBG = "../res/sounds/igbg.ogg"
MUSIC = True
TRACKSTATE = -1
GAMESTATE = -1
LY = 63241.077